name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.22" # Use the version of Go in your project
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./... # Run all tests
